# Generated by Django 4.2.7 on 2024-05-13 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_journey_average_speed_journey_duration_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gpspoint",
            name="heading",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="gpspoint",
            name="speed",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
    ]
